name: market-anomaly-risk
channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.13.1
  - scikit-learn=1.0.2
  - matplotlib=3.9.4
  - cvxpy=1.5.4
  - hmmlearn=0.3.3
  - ipython
  - ipykernel
  - jupyterlab
  - numexpr>=2.8.4
  - bottleneck>=1.3.6
  - pip
  - pip:
      - yfinance==0.2.54
